### ISSUE TITLE
Sprites and BustUps format + Header correction

### ISSUE THREAD

**Issue by Gunoshozo** [Manicsteiner/YuruCampHeaderAdder#1]
So I've figured out what kind of textures are stored in texbu.cpk, texsp.cpk, texmg.cpk ( this one is only for STRAH).
Had to feed raw data from file into unity and build texture from it with different formats.
![image](https://github.com/Manicsteiner/YuruCampHeaderAdder/assets/51006468/ec791066-0cef-42e4-b75b-b64e6dd27164)

Those textures are BC7, so we need another header with "DX10" in dwFourCC position and additional dds dxt10 header struct.
Also original files have a footer and the first 8 bytes are width and heights so you can just build your own header from that data (your file header-2700 for yuru camp is slightly incorrect in that regard, the original file is 1920x2716.
![image](https://github.com/Manicsteiner/YuruCampHeaderAdder/assets/51006468/d290915a-a5f9-4583-9cbc-56132466b99c)

I've experimented with bc7 textures generated with Nvidia Texture Tool Exporter and grab header from it's files.

Here is couple of examples of extracted textures:
![image](https://github.com/Manicsteiner/YuruCampHeaderAdder/assets/51006468/063f442b-e96b-46d0-9636-6bdab2c3528f)
![image](https://github.com/Manicsteiner/YuruCampHeaderAdder/assets/51006468/1f8f7ac1-ff73-486c-9f9f-f94e26648290)
![image](https://github.com/Manicsteiner/YuruCampHeaderAdder/assets/51006468/b5ed8bbf-29bd-4ee6-b907-7688bf9cc475)
![image](https://github.com/Manicsteiner/YuruCampHeaderAdder/assets/51006468/bbbe2483-6dac-400e-8d6c-fed634a49a84)
![image](https://github.com/Manicsteiner/YuruCampHeaderAdder/assets/51006468/e8f2a3d9-2ad7-4a18-806e-4ac779836b2d)

Forked your repo with updated code and header templates:
https://github.com/Gunoshozo/YuruCampHeaderAdder
and created pull request in case you want to merge those changes:
https://github.com/Manicsteiner/YuruCampHeaderAdder/pull/2

**Comment by Manicsteiner** [comment]
Great works, thankyou for your contribution ❤
